export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_PROVINCES_AND_CITIES='SET_PROVINCES_AND_CITIES'
export const SET_PROFILE='SET_PROFILE'
export const UPDATE_PROFILE='UPDATE_PROFILE'

export const UPDATE_STORE_PRODUCTS='UPDATE_STORE_PRODUCTS'
export const ADD_STORE_PRODUCTS='ADD_STORE_PRODUCTS'
export const UPDATE_SINGLE_PRODUCT='UPDATE_SINGLE_PRODUCT' // After submitting the feedback we need to update the product to add the new feedback
export const ADD_ALL_TAGS='ADD_ALL_TAGS'
export const ADD_CATEGORIES_SUBCATEGORIES='ADD_CATEGORIES_SUBCATEGORIES'
export const ADD_FILTERED_PRODUCT='ADD_FILTERED_PRODUCT'
export const ADD_IMAGE_SEARCHED_RESULT='ADD_IMAGE_SEARCHED_RESULT'

export const ADD_ORDERS='ADD_ORDERS'

export const ADD_TO_CART='ADD_PRODUCT_TO_CART'

export const ADD_CECKOUT_DATA='ADD_CECKOUT_DATA'

export const ADD_SHOULD_UPDATED_USER_ORDER ='UPDATE_USERORDERS'
