export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_PROVINCES_AND_CITIES='SET_PROVINCES_AND_CITIES'
export const SET_PROFILE='SET_PROFILE'
export const UPDATE_PROFILE='UPDATE_PROFILE'

export const UPDATE_STORE_PRODUCTS='UPDATE_STORE_PRODUCTS'
export const ADD_ALL_TAGS='ADD_ALL_TAGS'
export const ADD_CATEGORIES_SUBCATEGORIES='ADD_CATEGORIES_SUBCATEGORIES'